// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#pragma once

#include <memory>
#include <string>

namespace helloworld {

class HelloWorld {
public:
    virtual ~HelloWorld() {}

};

}  // namespace helloworld
