// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#include <jni.h>
#include <string>
#include <cstring>
#include <android/log.h>
#include <jni.h>



extern "C"
JNIEXPORT jstring JNICALL
Java_com_testcpp_helloworld_HelloWorldModule_getHelloWorld(JNIEnv * env, jobject thiz, jlong test) {
    std::string msg = "Native String...";
    jstring result;
    result = env->NewStringUTF(msg.c_str());
    return result;
}

//extern "C"
//JNIEXPORT jstring JNICALL
//Java_com_cppreactnative_helloworld_HelloWorld_00024CppProxy_create(JNIEnv *env, jclass, jobject instance , jstring msg) {
//    // TODO: implement create()
//
//    std::string msg0 = "Init" ;
//    jstring res;
//    res = env->NewStringUTF(msg0.c_str());
//    return res;
//}
