// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

package com.cppreactnative.helloworld;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class HelloWorld {
    public static HelloWorld test;

    public abstract int getHelloWorld();

    public static HelloWorld create()
    {
        return CppProxy.create();
    }

    private static final class CppProxy extends HelloWorld
    {
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        public static native int create(Object service, String msg);

        @Override
        public int getHelloWorld()
        {
            
            return create(this, "hello");
        }

        
    }
}
