// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#include <jni.h>

#include <android/log.h>


extern "C"
JNIEXPORT void JNICALL
Java_com_cppreactnative_helloworld_HelloWorld_00024CppProxy_nativeDestroy(JNIEnv *env, jobject thiz,
                                                                          jlong native_ref) {
    // TODO: implement nativeDestroy()
}

extern "C"
JNIEXPORT jstring JNICALL
Java_com_cppreactnative_helloworld_HelloWorld_00024CppProxy_native_1getHelloWorld(JNIEnv *env,
                                                                                  jobject thiz,
                                                                                  jlong _native_ref) {
    // TODO: implement native_getHelloWorld()
}

extern "C"
JNIEXPORT jint JNICALL
Java_com_cppreactnative_helloworld_HelloWorld_00024CppProxy_create(JNIEnv *env, jclass, jobject instance , jstring msg) {
    // TODO: implement create()
    return 1;
}